### ISSUE TITLE
Does not work with Firefox + Github Dark

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Selected-Tab-Color#1]
Yep doesnt work see?

![tabcolor](https://cloud.githubusercontent.com/assets/3521959/16931310/40435708-4d38-11e6-94cb-2c1b760e62a0.gif)

:(

**Comment by un1versal** [comment]
Found the culprit, apprently that second color didnt get stripped on update but removing it makes this work...

![tabcolor](https://cloud.githubusercontent.com/assets/3521959/16931476/0e8db270-4d39-11e6-82ac-c8da013cb822.gif)

**Comment by Mottie** [comment]
Oops, I'll get that fixed.

**Comment by un1versal** [comment]
<- Bug magnet

**Comment by Mottie** [comment]
Ok, all fixed... I just forgot to strip out those colors before pasting it into the userstyles site.

**Comment by un1versal** [comment]
This is very odd, **once in a while tabs stop being styled**, I have to edit the style, make some change (like add remove a space)  and click apply in order to get the styled tabs back.

Like this morning for instance after editing github.dark.css in relation to https://github.com/StylishThemes/GitHub-Dark/pull/348, it killed this style.
