### ISSUE TITLE
Style is being applied to all github.com sites

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Selected-Tab-Color#15]
Unlike GitHub-Dark this style is being applied to `github.com` so even things like https://styleguide.github.com get it. Should this, and any other GitHub user style, use the same regex that GitHub-Dark is?

```regex
^https?://((blog|gist|guides|help|raw|resources|status|developer)\.)?github\.com/((?!generated_pages/preview).)*$
```

**Comment by Mottie** [comment]
Hi @xt0rted!

This page shouldn't need the same regular expression. The style is small & I think the selectors are specific enough so as to not cause issues on pages other than those listed in the regular expression. Or, are you seeing a problem on any other pages?

**Comment by xt0rted** [comment]
The custom color (I use GitHub's default orange) is being applied to the tabs on https://styleguide.github.com/primer/components/navigation/ because of

https://github.com/StylishThemes/GitHub-Selected-Tab-Color/blob/c64af05591d6f11394a5432b329b1ae0e8df0f9b/github-selected-tab-color.user.css#L13

This is why I was wondering if it should be updated.

I use this as a reference when looking up control selectors, and for my own curiosity, so it's not too bad if our custom styles get applied but I wasn't sure if this was deliberate or not.

**Comment by Mottie** [comment]
It wasn't deliberate. It was an oversight. If you think it needs it, we can switch to the regexp.

**Comment by the-j0k3r** [comment]
I think styleguide need to be dark, thats what I think :) burnt another retina layer.
