### ISSUE TITLE
Selected top tabs have different height (shift text down)

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Selected-Tab-Color#16]
The issue reported in https://github.com/StylishThemes/GitHub-Dark/issues/895 is happening now when using this style.

Ive removed https://github.com/StylishThemes/GitHub-Selected-Tab-Color/blob/05b0fb1c97c9102ef7ed22921591c2d52e2325e7/github-selected-tab-color.user.css#L45-L48 but it has no effects now.

![generic](https://user-images.githubusercontent.com/31389848/54973895-35539380-4f92-11e9-8da2-1906e70181a6.gif)

@silverwind

**Comment by the-j0k3r** [comment]
Potential fix

```css
  body .reponav .reponav-item.selected {
    padding-top: 7px !important;
  }
```

![generic](https://user-images.githubusercontent.com/31389848/54974887-ced07480-4f95-11e9-9a27-126ef7270f99.gif)


and also remove now dead CSS of position static.

**Comment by silverwind** [comment]
GHD reduces the border to 1px and re-adds the lost 2px of height back via `padding-top`. Note that the tabs on the org page (`.pagehead-tabs-item`) are 1px taller then on the repo.
