### ISSUE TITLE
fs-extra

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Selected-Tab-Color#17]
@silverwind see
https://github.com/StylishThemes/GitHub-Selected-Tab-Color/blob/958611c6bd350c56337a89501961f844943fedfa/tools/fix-perfectionist.js#L4

We dont actually have fs-extra in package.json, should there be or should this be removed?

**Comment by xt0rted** [comment]
Right now that's a transient dependency from `ver`. Since it's being used directly I'd say it should be made a direct dependency.

**Comment by silverwind** [comment]
If everyone is ok with using Node.js 12 we can probably replace this dependency with `require("fs").promises`. It's available on 10 too, but the experimental warning was only removed in 12.

**Comment by xt0rted** [comment]
I've been on node 12 for awhile now so I'm ok with that.

**Comment by the-j0k3r** [comment]
Im OK with whatever works better here. Though this repo doesnt actually need perfectionist, one line per selector works good for small styles such as this.

**Comment by silverwind** [comment]
Okay, Node.js 12 or greater is now required. I'm a bit worried because [Arch](https://www.archlinux.org/packages/?name=nodejs) has not updated to 12 yet, but I guess I can live with the warning until then.

**Comment by silverwind** [comment]
Actually `engines.node` at 10 is fine. The API is there and functional in 10,11 and 12.
