### ISSUE TITLE
Feature request: Support repo filter selector button - selected color

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Selected-Tab-Color#2]
![tabcolor](https://cloud.githubusercontent.com/assets/3521959/16932345/b150b60c-4d3d-11e6-8301-54f36141e8c4.gif)

I tried adding it the classes on that seems to be

`<button type="button" class="btn-link repo-filter text-small text-muted js-repo-filter-tab filter-selected" data-filter=".public" data-ga-click="Dashboard, click, Repo list filter - context:user filter:public">Public</button>`

Obviously needs a masters touch :+1: 

Doesnt like my moldy cheese Mottie... what will I do now? Cry myself to sleep? `</sarcasm>`
but none of that worked...

**Comment by Mottie** [comment]
Hi @un1versal!

Done. And userstyles has also been updated.

**Comment by Mottie** [comment]
By the way, you know you can click on the "expand pane" button to see the actual styles being applied to an element.

![pane](https://cloud.githubusercontent.com/assets/136959/16933753/0730037a-4d16-11e6-8118-ebfb29e3ad3a.gif)

**Comment by un1versal** [comment]
> By the way, you know you can click on the "expand pane" button to see the actual styles being applied to an element.

Well I do for sure now ! ;)
