### ISSUE TITLE
Add GitHub Status tabs

### ISSUE THREAD

**Issue by un1versal** [StylishThemes/GitHub-Selected-Tab-Color#4]
class is `.tabs .tab` url https://status.github.com/

I can make this work with GitHub Dark Script and untsyled

![links](https://cloud.githubusercontent.com/assets/3521959/16941587/ec3ada72-4d88-11e6-9c63-2afe4e9757cd.gif)

from

```
  pagehead-tabs-item.selected, .reponav-item.selected, .btn-link.selected,
  .tabnav-tab.selected {
    border-top-width: 3px !important;
    border-top-color: #5E8ACC !important;
  }
```

to

```
  pagehead-tabs-item.selected, .reponav-item.selected, .btn-link.selected,
  .tabnav-tab.selected, .tabs .tab {
    border-top-width: 3px !important;
    border-top-color: #5E8ACC !important;
  }
```

 but not the stylish version, even with a comma between `.tabs, .tab` hence issue

**Comment by Mottie** [comment]
Oops, I closed the PR that added this, it had extra definitions that weren't needed anyway.
