### ISSUE TITLE
Sub tabs on pull request ignored and Userstyles + Stylus issue

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Selected-Tab-Color#9]
![capture](https://user-images.githubusercontent.com/31389848/30776200-3432eeae-a09a-11e7-8bb7-3fa6455d81a6.PNG)

example link https://github.com/StylishThemes/GitHub-Dark/pull/518

```
<a href="/StylishThemes/GitHub-Dark/pull/518" class="tabnav-tab selected js-pjax-history-navigate">
      <svg aria-hidden="true" class="octicon octicon-comment-discussion" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path fill-rule="evenodd" d="M15 1H6c-.55 0-1 .45-1 1v2H1c-.55 0-1 .45-1 1v6c0 .55.45 1 1 1h1v3l3-3h4c.55 0 1-.45 1-1V9h1l3 3V9h1c.55 0 1-.45 1-1V2c0-.55-.45-1-1-1zM9 11H4.5L3 12.5V11H1V5h4v3c0 .55.45 1 1 1h3v2zm6-3h-2v1.5L11.5 8H6V2h9v6z"></path></svg>
      Conversation

      <span id="conversation_tab_counter" class="Counter">
        6
      </span>
    </a>
```

As far as I can tell this is part of the css https://github.com/StylishThemes/GitHub-Selected-Tab-Color/blob/master/github-selected-tab-color.css#L11

The other issue is wanted to match my github dark color after installing this into stylus, but I opened the dialog selected my color and userstyles didn't give me a choice to update style.
Solution remove and re-install. Not sure whats going on there.

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Thanks for letting us know.

There is nothing I can do about the userstyles site... this style is also available from http://freestyler.ws/style/142700/github-selected-tab-color.

**Comment by the-j0k3r** [comment]
Heads up Userstyles site was Stylus bug https://github.com/openstyles/stylus/issues/184#issuecomment-332643568

fixed  so it seems so far. :)
